### ISSUE TITLE
What if it return bad gateway 502

### ISSUE THREAD

**Issue by hilmanski** [testdrivenio/fastapi-docker-traefik#1]
Hi. Thanks for your great post on Testdrive.io
I try to re-implement it on my own site, unfortunately it return bad gateway 502.

May I ask, why in `docker-compose.prod.yml` , you remove the command part which should run the uvicorn server?

```
 command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 #this is gone in prod docker compose
```

**Comment by frgfm** [comment]
Hi @mjhea0,

Similarly to the issue author, I cannot get anything else than 502 bad gateway following your article.
To narrow down the problem, I even removed the postgre part so that the python code is reduced to:
```python
from fastapi import FastAPI

app = FastAPI(title="FastAPI, Docker, and Traefik")


@app.get("/")
def read_root():
    return {"hello": "world"}
```

Without traefik everything goes well, but adding your suggested toml for traefik and docker compose, I can access the dashboard but I consistently get a `502 Bad Gateway` on http://fastapi.localhost:8008/
I've been coming back to this article several times and thought it was a problem on my side. So when I saw that the article was updated, I tried my luck and I was out of ideas. But seeing this issue, I just thought that there might be a reason.

Any idea where that could come from? @hilmanski how did you manage to solve your problem? :pray: 

Thanks in advance!

**Comment by frgfm** [comment]
Any update @mjhea0 @hilmanski ? :pray:

**Comment by frgfm** [comment]
Hello @mjhea0 @hilmanski, would you mind sharing how you got around this problem?
There is no information whatsoever why the issue was closed or how any of you might have solved it :sweat_smile: 

Thanks in advance :pray:

**Comment by mjhea0** [comment]
I couldn't recreate on my end. Sorry, @frgfm.
